version: '3'

services:
    app:
        container_name: nortada-ecommerce-clone-frontend
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        stdin_open: true
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development